### PR TITLE
rework mesecons debug to be more flexible

### PR DESCRIPTION
**Pull request by fluxionary**
I rewrote (much of) this mod in order to make it more useful for the "Your Land" server, and wanted to give you an option to incorporate part or all of the changes. 

The main difference is that instead of penalizing mapblocks based on whether mesecons usage exceeds a fixed number of microseconds, the mod now penalizes things based on
1. How over-loaded the server currently is (lag)
2. How much of that load is due to mesecons itself
3. How much a particular mapblock contributes to the overload. 

Other changes:
* Made whitelisting actually work
* Store the whitelist in `mod_storage` instead of a custom file
* Added settings that can be changed in `minetest.conf` or via a new chat command
* Refactoring and cleanup

The changes have yet to go through rigorous testing on the live server, though multiplayer testing on a dev server seemed to indicate things are working as I'd expect. 

Any feedback would be appreciated, or feel free to just close/ignore this PR as overly-ambitious :)

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
> Any feedback would be appreciated, or feel free to just close/ignore this PR as overly-ambitious :)

Wow, thats quite a lot of work but i think it is going in the right direction :+1: 

Does that currently work well on the YL server?

**Comment by fluxionary** [comment]
> Does that currently work well on the YL server?

It works well on the test server, but that's not totally representative of a live server. And YL isn't very machine-heavy in the first place. I don't have a timeline for when it will get installed on the live server, but I'll post updates as I think it's relevant.

**Comment by fluxionary** [comment]
Just an update. The code is finally live on the main server, and has at least one major bug - it doesn't seem to actually apply the penalties (!). I'm working on that, but probably won't get it resolved until at least tomorrow.

**Comment by BuckarooBanzay** [comment]
> I'm working on that, but probably won't get it resolved until at least tomorrow.

no pressure ;)

**Comment by fluxionary** [comment]
Figured out why the penalty wasn't being applied, it's now going through another round of testing on the YL test server (will be a few days until I've got results).

**Comment by fluxionary** [comment]
The current version of the code is live on YL now, I'll hopefully post an update of how that goes, in a few days.

**Comment by fluxionary** [comment]
I'm personally happy with how the mod is performing on Your-Land.

**Comment by BuckarooBanzay** [comment]
> I'm personally happy with how the mod is performing on Your-Land.

Nice :+1: do you intend to add more commits or can i go ahead with testing/merging?

**Comment by fluxionary** [comment]
Not planning on adding more commits at the moment, though perhaps I should document the use of the parameters.

**Comment by BuckarooBanzay** [comment]
tested it too on a pandorabox-test instance, no issues so far :+1: merging this...

**Pull request merged**
